### ISSUE TITLE
Saving RSS fetched text in a central database

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/rss-data#1]
- Save daily RSS texts into a central database table
- Use the tidyRSS R package and the function tidyfeed to read RSS sources
- The database table will have a fixed column structure
- A configuration R file is used to:
  - List the RSS sources to be checked
  - Map the fields from each RSS source to the database table
  - Determine how often a check is made for new entries from each RSS source. Note that, RSS sources are often updated more than once per day. Thus, a check should also be made if data is not transferred to the database in duplicate.
- An option to download the database -> `rss-api`

**Comment by arunge** [comment]
@SarahWagner 

- You may check the [iso-data](https://github.com/Pandora-IsoMemo/iso-data/tree/main/R) repository as a draft for an ETL that we are already using, or use another draft
- as menioned above we can use `tidyRSS::tidyfeed()`
  > Use the tidyRSS R package and the function tidyfeed to read RSS sources

```R
# Feed CNN
feed1 <- tidyRSS::tidyfeed("http://rss.cnn.com/rss/edition_world.rss")

# Extract a link from the feed, here the first
link <- feed1[[mapping()[["Link"]]]][[1]]

# Fetch the content of the link
page <- httr::GET(link, httr::timeout(30))
page_content <- httr::content(page, as = "text")

# Parse the HTML content
html <- rvest::read_html(page_content)

# Extract the main text content
# You might need to adjust the CSS selector based on the specific structure of the web page
html %>%
  rvest::html_nodes("p") %>% # Adjust this selector to target the main content
  rvest::html_text() %>%
  stringr::str_squish() %>%
  paste(collapse = " ") # Combine all text nodes into a single string
```

- in order to setup the configuration
  > A configuration R file is used to:
  >  - List the RSS sources to be checked
  >  - Map the fields from each RSS source to the database table

  we discussed to define a `yaml` file, which might look like follows:

`inst/config.yaml`
```yaml
# RSS sources
source:
  Example:
    url: "https://www.example.com/feed"
    name: "Example Feed"
    description: "This is an example feed"
    category: "Example"

# mapping for all columns of the target table on the database
# Please, add columns as needed (e.g. `date_last_updated`, `id`, ...)!
fieldMapping:
  Example:
    source: "feed_title"
    title: "item_title"
    link: "item_link"
    text: "item_text"
```

Feel free to open issues to your needs! Please, let me know if you have questions! :blush:
