### ISSUE TITLE
New database server

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/rss-data#3]
From https://github.com/Pandora-IsoMemo/rss-data/issues/1#issue-2386464673:

> our IT will setup a new server. The database system to be used should allow for a very large content.

@SarahWagner you suggested to use [MongoDB](https://www.mongodb.com/de-de) in the future, which is better for large datasets than our current database. I will discuss options with @isomemo in our next meeting.

Currently, we only have example data and write it into the [existing database](https://github.com/Pandora-IsoMemo/rss-data/issues/1#issuecomment-2206657663). In order to understand _how large_ our data will be, we need at least some of the RSS sources that we will use in the future for analysis.

@isomemo Could you provide a list of RSS sources?

Then we can check the sources and make suggestions regarding the specifications for the new server.

**Comment by isomemo** [comment]
@arunge I have a RSS source list: 
[News Project RSS Feeds.docx](https://github.com/user-attachments/files/16846675/News.Project.RSS.Feeds.docx)

however, still missing are the selected fields for each. Jian will colaborate on this project and will help with this selection. Can you please add him as a project member so that he can comment?

**Comment by arunge** [comment]
@isomemo I invited Jian to this repository.

@policybot2020 Currently we use example rss feeds in our ETL. You can find the config here: https://github.com/Pandora-IsoMemo/rss-data/blob/main/config.yaml

Could you update the config file with respect to the list provided by @isomemo (see [above](https://github.com/Pandora-IsoMemo/rss-data/issues/3#issuecomment-2326075454))?

Please let me know if you have any questions! Thanks in advance! :blush:

**Comment by policybot2020** [comment]
@arunge @isomemo Is this the NLP text analysis project? I am not aware of this task.

**Comment by arunge** [comment]
@SarahWagner Please, check the document [above](https://github.com/Pandora-IsoMemo/rss-data/issues/3#issuecomment-2326075454) for a list of sources. Let me know when you can roughly estimate how much storage will be needed if we want to save news feeds daily for a year for all the sources given in the document.

In the next step we can discuss options of storage and cleaning up. Thanks! :pray:

**Comment by arunge** [comment]
@policybot2020

@isomemo mentioned that you will help to

> Map the fields from each RSS source to the database table (https://github.com/Pandora-IsoMemo/rss-data/issues/1#issue-2386464673)

The list of RSS sources is given [above](https://github.com/Pandora-IsoMemo/rss-data/issues/3#issuecomment-2326075454) in a word document.

We now require a complete list of sources of RSS feeds in the format below (compare with our [config.yaml](https://github.com/Pandora-IsoMemo/rss-data/blob/main/config.yaml) ):

```
# RSS sources
sources:
  Source_1:
    url: "http://rss.cnn.com/rss/edition_world.rss"
    name: "CNN" # not used
    description: "Edition World" # not used
    category: "Example 1" # not used
    id: 1
  Source_2:
    url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    name: "BBC"
    description: "News World"
    category: "Example 2"
    id: 2
```
The fields `url` and `name` are required, `description` and `category` are optional.

----

Based on this config file each source will be read using: `tidyRSS::tidyfeed(<url>)`

You can test output with, e.g.
```R
> tidyRSS::tidyfeed("http://rss.cnn.com/rss/edition_world.rss")
GET request successful. Parsing...

# A tibble: 29 × 14
   feed_title                feed_link feed_description feed_language feed_pub_date       feed_last_build_date feed_generator feed_ttl item_title item_link item_description
   <chr>                     <chr>     <chr>            <chr>         <dttm>              <dttm>               <chr>          <chr>    <chr>      <chr>     <chr>           
 1 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Markets … https://…  NA             
 2 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Still ha… https://… "So far this ta…
 3 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Retail s… https://… "Spending at US…
 4 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Analysis… https://… "This is it."   
 5 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Silicon … https://… "When customers…
 6 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Not only… https://… "Lake Powell, t…
 7 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "These we… https://… "Air pollution …
 8 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Big-box … https://… "As the US atte…
 9 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Look of … https://… "Bringing the s…
10 CNN.com - RSS Channel - … https://… CNN.com deliver… en-US         2023-04-24 22:55:36 2024-08-22 15:32:30  coredev-bumbl… 10       "Scientis… https://… "\"Old Masters\…
# ℹ 19 more rows
# ℹ 3 more variables: item_pub_date <dttm>, item_guid <chr>, item_category <list>
# ℹ Use `print(n = ...)` to see more rows
```

For our examples `tidyfeed()` always returned the same columns:

```R
c("feed_title", "feed_link", "feed_description", "feed_language", 
"feed_pub_date", "feed_last_build_date", "feed_generator", "feed_ttl", 
"item_title", "item_link", "item_description", "item_pub_date", 
"item_guid", "item_category")
```

Therefore, we have currently [one mapping for all sources](https://github.com/Pandora-IsoMemo/rss-data/blob/main/config.yaml) and use following of the columns:

```
# Mapping for all fields of the rss sources
# Add columns as needed
# Only change the values (right from the colon), not the keys!
rssMapping:
  source_id: "source_id" # generated here
  source: "feed_title"
  title: "item_title"
  link: "item_link"
  text: "item_text"
  timestamp_feed_updated: "feed_last_build_date"
  timestamp_item_published: "item_pub_date"
```

If fields are missing our ETL does catch this and gives a warning:

https://github.com/Pandora-IsoMemo/rss-data/blob/cec72249157ab5fa863656a88d1183d6891bddd7/R/02_read_rss.R#L19-L33

However, at least `"item_link"` **or** `"item_text"` should be available. 

Could you please 
- complete the list of sources in our [config.yaml](https://github.com/Pandora-IsoMemo/rss-data/blob/main/config.yaml)? Feel free to open a pull request with an updated version of the `config.yaml`.
- let me know if there are sources were both `"item_link"` **and** `"item_text"` are missing?

Let me know if you have questions! Thanks in advance! :pray:
